# Uncomment this line to define a global platform for your project
platform :ios, '8.2'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Ubergang', :path => '~/Workspace/mobile/Ubergang'

target 'TweenApp' do

end 